import React, { useState, useEffect } from 'react';
import { Recipe, User, FoodItem } from '../types';

interface RecipesProps {
  preferences: User;
  onUpdatePreferences: (updates: Partial<User>) => void;
  inventory: FoodItem[];
}

export const Recipes: React.FC<RecipesProps> = ({
  preferences,
  onUpdatePreferences,
  inventory
}) => {
  const [recipes, setRecipes] = useState<Recipe[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedIngredient, setSelectedIngredient] = useState<string>('all');

  const fetchRecipes = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const email = preferences ? preferences.email : '';
      const response = await fetch('https://pdd-9fqv.onrender.com/api/recipes', {
        headers: { 'x-user-email': email }
      });
      const data = await response.json();
      if (data.success) {
        setRecipes(data.recipes);
      } else {
        setError('Failed to load recipe suggestions.');
      }
    } catch (err) {
      setError('Could not connect to backend. Verify Node.js is running.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchRecipes();
  }, [preferences.servings, preferences.audienceMode]);

  const handleServingsChange = (change: number) => {
    const newVal = Math.max(1, Math.min(10, preferences.servings + change));
    onUpdatePreferences({ servings: newVal });
  };

  const handleMembersChange = (change: number) => {
    const current = preferences.membersCount || 2;
    const newVal = Math.max(1, Math.min(20, current + change));
    onUpdatePreferences({ membersCount: newVal });
  };

  const handleAudienceChange = (mode: 'Regular' | 'Kid-friendly' | 'Gourmet') => {
    onUpdatePreferences({ audienceMode: mode });
  };

  // Estimate quantity to buy for household
  const getBuyQuantity = (baseQty: number) => {
    const members = preferences.membersCount || 2;
    const baseServings = preferences.servings || 2;
    return parseFloat(((baseQty / baseServings) * members).toFixed(2));
  };

  // Client-side filtering: exclude recipes using spoiled items or cooked foods in the active inventory
  const activeRecipes = recipes.filter(r => {
    const matchingItem = inventory.find(item => 
      item.name.toLowerCase() === r.primaryIngredient.toLowerCase() ||
      r.primaryIngredient.toLowerCase().includes(item.name.toLowerCase()) ||
      item.name.toLowerCase().includes(r.primaryIngredient.toLowerCase())
    );
    if (matchingItem) {
      if (matchingItem.status === 'Spoiled' || matchingItem.isCooked || matchingItem.category === 'cooked food') {
        return false;
      }
    }
    return true;
  });

  const uniqueIngredients = Array.from(new Set(activeRecipes.map(r => r.primaryIngredient)));

  return (
    <div style={{ maxWidth: '900px', margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1>Smart Recipe Assistant</h1>
          <p style={{ color: 'var(--text-muted)' }}>
            Autogenerated recipe combinations using raw ingredients nearing decay.
          </p>
        </div>

        {/* Controls Row */}
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          {/* Members count */}
          <div className="glass-card" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.5rem 1rem', borderColor: 'rgba(0,230,118,0.3)' }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>👨‍👩‍👧 Members:</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <button className="btn-secondary" style={{ padding: '0.2rem 0.5rem', borderRadius: '4px', border: 'none' }} onClick={() => handleMembersChange(-1)}>−</button>
              <strong style={{ minWidth: '1.5rem', textAlign: 'center', color: 'var(--color-fresh)' }}>{preferences.membersCount || 2}</strong>
              <button className="btn-secondary" style={{ padding: '0.2rem 0.5rem', borderRadius: '4px', border: 'none' }} onClick={() => handleMembersChange(1)}>+</button>
            </div>
          </div>

          {/* Recipe servings */}
          <div className="glass-card" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.5rem 1rem' }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Servings:</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <button className="btn-secondary" style={{ padding: '0.2rem 0.5rem', borderRadius: '4px', border: 'none' }} onClick={() => handleServingsChange(-1)}>−</button>
              <strong style={{ minWidth: '1.5rem', textAlign: 'center' }}>{preferences.servings}</strong>
              <button className="btn-secondary" style={{ padding: '0.2rem 0.5rem', borderRadius: '4px', border: 'none' }} onClick={() => handleServingsChange(1)}>+</button>
            </div>
          </div>

          {/* Audience mode */}
          <div className="glass-card" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem' }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginRight: '0.25rem' }}>Audience:</span>
            <div style={{ display: 'flex', gap: '2px', background: 'var(--bg-secondary)', borderRadius: '8px', padding: '2px' }}>
              {(['Regular', 'Kid-friendly', 'Gourmet'] as const).map(mode => (
                <button key={mode} className="btn-secondary"
                  style={{ padding: '0.3rem 0.6rem', fontSize: '0.8rem', border: 'none', background: preferences.audienceMode === mode ? 'var(--glass-border)' : 'transparent', color: preferences.audienceMode === mode ? '#fff' : 'var(--text-muted)' }}
                  onClick={() => handleAudienceChange(mode)}>
                  {mode === 'Kid-friendly' ? 'Kid-friendly 👶' : mode}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Members quantity advice banner */}
      {(preferences.membersCount || 2) > 0 && (
        <div className="glass-card" style={{ marginBottom: '1.5rem', padding: '0.85rem 1.25rem', borderColor: 'rgba(0,230,118,0.25)', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ fontSize: '1.2rem' }}>🛒</span>
          <div>
            <span style={{ fontSize: '0.85rem', fontWeight: 600 }}>Cooking for {preferences.membersCount || 2} member{(preferences.membersCount || 2) > 1 ? 's' : ''}</span>
            <span style={{ fontSize: '0.82rem', color: 'var(--text-muted)', marginLeft: '0.5rem' }}>— ingredient quantities below are auto-scaled. Check the "Buy Quantity" column to know how much to purchase next time.</span>
          </div>
        </div>
      )}

      {isLoading ? (
        <div style={{ textAlign: 'center', padding: '4rem' }}>
          <div style={{ border: '4px solid rgba(255,255,255,0.1)', borderTop: '4px solid var(--color-fresh)', borderRadius: '50%', width: '40px', height: '40px', animation: 'spin 1s linear infinite', margin: '0 auto' }} />
          <p style={{ marginTop: '1rem', color: 'var(--text-muted)' }}>Calculating ingredient values...</p>
        </div>
      ) : error ? (
        <div className="glass-card" style={{ textAlign: 'center', padding: '3rem', borderColor: 'var(--color-spoiled)' }}>
          <p style={{ color: 'var(--color-spoiled)' }}>{error}</p>
          <button className="btn-secondary" style={{ marginTop: '1rem' }} onClick={fetchRecipes}>Retry Sync</button>
        </div>
      ) : activeRecipes.length === 0 ? (
        <div className="glass-card" style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-muted)' }}>
          <p style={{ fontSize: '1.2rem', marginBottom: '0.5rem' }}>No recipe matches available.</p>
          <p style={{ fontSize: '0.9rem' }}>Recipes are only generated for raw (uncooked) and unspoiled food items. Add uncooked fruits/vegetables to view suggestions.</p>
        </div>
      ) : (
        <div>
          {/* Ingredient Role Filter Bar */}
          {uniqueIngredients.length > 0 && (
            <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '2rem', flexWrap: 'wrap', alignItems: 'center', background: 'var(--glass-bg)', padding: '1rem', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 600, marginRight: '0.5rem' }}>🎯 Scanned Ingredient Role:</span>
              <button
                className="btn-secondary"
                style={{
                  padding: '0.4rem 0.8rem', fontSize: '0.8rem',
                  borderColor: selectedIngredient === 'all' ? 'var(--color-fresh)' : 'var(--glass-border)',
                  background: selectedIngredient === 'all' ? 'rgba(0,230,118,0.05)' : 'var(--glass-bg)',
                  color: selectedIngredient === 'all' ? 'var(--color-fresh)' : 'inherit'
                }}
                onClick={() => setSelectedIngredient('all')}
              >
                All Matches
              </button>
              {uniqueIngredients.map(ing => (
                <button
                  key={ing}
                  className="btn-secondary"
                  style={{
                    padding: '0.4rem 0.8rem', fontSize: '0.8rem',
                    borderColor: selectedIngredient === ing ? 'var(--color-fresh)' : 'var(--glass-border)',
                    background: selectedIngredient === ing ? 'rgba(0,230,118,0.05)' : 'var(--glass-bg)',
                    color: selectedIngredient === ing ? 'var(--color-fresh)' : 'inherit'
                  }}
                  onClick={() => setSelectedIngredient(ing)}
                >
                  {ing}
                </button>
              ))}
            </div>
          )}

          <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
            {activeRecipes
              .filter(r => selectedIngredient === 'all' ? true : r.primaryIngredient === selectedIngredient)
              .map((recipe, idx) => (
                <div key={idx} className="glass-card" style={{ padding: '2rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem', borderBottom: '1px solid var(--glass-border)', paddingBottom: '1.25rem', marginBottom: '1.5rem' }}>
                    <div>
                      <span style={{ fontSize: '0.75rem', textTransform: 'uppercase', color: 'var(--color-warning)', fontWeight: 700, letterSpacing: '1px' }}>
                        💡 Matches: {recipe.primaryIngredient} ({recipe.daysToExpiry} days left)
                      </span>
                      <h2 style={{ margin: '0.25rem 0 0.5rem', fontSize: '1.6rem' }}>{recipe.title}</h2>
                      <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem' }}>{recipe.description}</p>
                    </div>
                    {recipe.chiliLevel === 'high' && (
                      <span className="user-score-badge spoiled-badge" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.25rem' }}>
                        🌶️ Spicy Recipe
                      </span>
                    )}
                  </div>

                  {recipe.advice && (
                    <div style={{
                      background: preferences.audienceMode === 'Kid-friendly' ? 'var(--color-fresh-bg)' : 'rgba(255,234,0,0.05)',
                      border: `1px solid ${preferences.audienceMode === 'Kid-friendly' ? 'var(--color-fresh)' : 'rgba(255,234,0,0.2)'}`,
                      color: preferences.audienceMode === 'Kid-friendly' ? 'var(--color-fresh)' : 'var(--color-warning)',
                      padding: '0.75rem 1rem', borderRadius: '8px', fontSize: '0.85rem', fontWeight: 500, marginBottom: '1.5rem'
                    }}>
                      {recipe.advice}
                    </div>
                  )}

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '2.5rem' }}>
                    {/* Ingredients table with buy quantity */}
                    <div>
                      <h3 style={{ marginBottom: '1rem', fontSize: '1.1rem' }}>Ingredients List</h3>
                      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                        <thead>
                          <tr style={{ borderBottom: '1px solid var(--glass-border)' }}>
                            <th style={{ textAlign: 'left', padding: '0.4rem 0', color: 'var(--text-muted)', fontWeight: 600 }}>Ingredient</th>
                            <th style={{ textAlign: 'right', padding: '0.4rem 0', color: 'var(--text-muted)', fontWeight: 600 }}>Recipe</th>
                            <th style={{ textAlign: 'right', padding: '0.4rem 0', color: 'var(--color-fresh)', fontWeight: 600 }}>Buy Qty</th>
                          </tr>
                        </thead>
                        <tbody>
                          {recipe.ingredients.map((ing, i) => (
                            <tr key={i} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                              <td style={{ padding: '0.6rem 0', color: 'var(--text-muted)' }}>{ing.name}</td>
                              <td style={{ padding: '0.6rem 0', textAlign: 'right', fontWeight: 700 }}>{ing.qty} {ing.unit}</td>
                              <td style={{ padding: '0.6rem 0', textAlign: 'right', fontWeight: 700, color: 'var(--color-fresh)' }}>{getBuyQuantity(ing.qty)} {ing.unit}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                      <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginTop: '0.5rem' }}>
                        Buy Qty = scaled for {preferences.membersCount || 2} member{(preferences.membersCount || 2) > 1 ? 's' : ''}
                      </p>
                    </div>

                    {/* Steps */}
                    <div>
                      <h3 style={{ marginBottom: '1rem', fontSize: '1.1rem' }}>Directions</h3>
                      <ol style={{ paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.85rem', fontSize: '0.9rem', lineHeight: '1.6', color: 'var(--text-muted)' }}>
                        {recipe.steps.map((step, sIdx) => (
                          <li key={sIdx}><span style={{ color: 'var(--text-main)' }}>{step}</span></li>
                        ))}
                      </ol>
                    </div>
                  </div>
                </div>
              ))}
          </div>
        </div>
      )}
    </div>
  );
};
